Repository tektoncd/experimental, pull requests merged in 2019-12, with the labels that each got.

#383 Add Openshift RoutesClientset to Resource. Use clientset for Route cr…
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/docs/Architecture.md
  webhooks-extension/docs/InstallPrereqs.md
  webhooks-extension/pkg/endpoints/shared-test-funcs.go
  webhooks-extension/pkg/endpoints/types.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/L

#380 Issue 375: Fix for org repositories not triggering pipelineruns
  webhooks-extension/cmd/interceptor/interceptor.go
  webhooks-extension/cmd/interceptor/interceptor_test.go
Labels: approved, lgtm, size/S

#382 Add a suggested image tag to the webhook event payload
  webhooks-extension/cmd/interceptor/interceptor.go
  webhooks-extension/cmd/interceptor/interceptor_test.go
  webhooks-extension/docs/Parameters.md
Labels: approved, lgtm, size/L

#379 WIP: Use go-github client to replace rest request for pubsubhubbub
  webhooks-extension/Gopkg.lock
  webhooks-extension/README.md
  webhooks-extension/config/extension-deployment.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/docs/InstallPrereqs.md
  webhooks-extension/docs/WebhookSecurity.md
  webhooks-extension/pkg/endpoints/git.go
  webhooks-extension/pkg/endpoints/github.go
  webhooks-extension/pkg/endpoints/github_test.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/pkg/utils/utils.go
Labels: approved, lgtm, size/XL

#390 Fixed bad URL for webhooks 'Success' message
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/monitor.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
Labels: approved, lgtm, size/S

#392 Update Octant Plugin Documentation
  octant-plugin/README.md
Labels: approved, lgtm, size/M

#393 Add Triggers to the webhooks ClusterRole
  webhooks-extension/config/extension-deployment.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
Labels: approved, lgtm, size/XS

#398 Modify ko-ci image referenced in release process yaml
  webhooks-extension/tekton/publish.yaml
Labels: approved, lgtm, size/XS

#402 Fix service account name picked up by monitor task
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/monitor.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
Labels: approved, lgtm, size/S

#403 De-duplicate config yaml using Kustomize
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/base/200-clusterrole-eventListener.yaml
  webhooks-extension/base/200-clusterrole.yaml
  webhooks-extension/base/200-role.yaml
  webhooks-extension/base/200-serviceaccount-eventListener.yaml
  webhooks-extension/base/200-serviceaccount.yaml
  webhooks-extension/base/201-clusterrolebinding-eventListener.yaml
  webhooks-extension/base/201-clusterrolebinding.yaml
  webhooks-extension/base/201-rolebinding.yaml
  webhooks-extension/base/300-extension-deployment.yaml
  webhooks-extension/base/300-extension-service.yaml
  webhooks-extension/base/300-interceptor-deployment.yaml
  webhooks-extension/base/300-interceptor-service.yaml
  webhooks-extension/base/400-monitor-task.yaml
  webhooks-extension/base/400-monitor-triggerbinding.yaml
  webhooks-extension/base/400-monitor-triggertemplate.yaml
  webhooks-extension/base/kustomization.yaml
  webhooks-extension/config/extension-deployment.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/docs/InstallNightlyBuild.md
  webhooks-extension/docs/Uninstall.md
  webhooks-extension/overlays/development/kustomization.yaml
  webhooks-extension/overlays/latest/kustomization.yaml
  webhooks-extension/overlays/openshift-all/clusterRole-patch.yaml
  webhooks-extension/overlays/openshift-all/deployment-patch.yaml
  webhooks-extension/overlays/openshift-all/kustomization.yaml
  webhooks-extension/overlays/openshift-all/role-patch.yaml
  webhooks-extension/overlays/openshift-development/kustomization.yaml
  webhooks-extension/overlays/openshift-latest/kustomization.yaml
  webhooks-extension/overlays/openshift-release/kustomization.yaml
  webhooks-extension/overlays/plainkube-all/deployment-patch.yaml
  webhooks-extension/overlays/plainkube-all/kustomization.yaml
  webhooks-extension/overlays/plainkube-all/role-patch.yaml
  webhooks-extension/overlays/release/kustomization.yaml
  webhooks-extension/test/README.md
  webhooks-extension/test/presubmit-tests.sh
  webhooks-extension/test/util.sh
Labels: approved, lgtm, size/XXL

#410 Use Json6902 patch for Role and ClusterRole
  webhooks-extension/overlays/openshift-all/cluster-role-patch-json.yaml
  webhooks-extension/overlays/openshift-all/clusterRole-patch.yaml
  webhooks-extension/overlays/openshift-all/kustomization.yaml
  webhooks-extension/overlays/openshift-all/role-patch-json.yaml
  webhooks-extension/overlays/openshift-all/role-patch.yaml
Labels: approved, lgtm, size/M

#411 Fix RBAC overlay on plain Kube
  webhooks-extension/overlays/plainkube-all/kustomization.yaml
  webhooks-extension/overlays/plainkube-all/role-patch-json.yaml
  webhooks-extension/overlays/plainkube-all/role-patch.yaml
Labels: approved, lgtm, size/M

#412 Use kustomize in release process
  webhooks-extension/tekton/publish.yaml
Labels: approved, lgtm, size/XS

#407 Preserve existing comments for monitor task
  webhooks-extension/base/400-monitor-task.yaml
Labels: approved, lgtm, size/XS

#413 Initial commit of TekDoc tool
  tekdoc/OWNERS
  tekdoc/README.md
  tekdoc/dummy_test.go
  tekdoc/go.mod
  tekdoc/go.sum
  tekdoc/main.go
  tekdoc/test/presubmit-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XL

#415 Skip instead of failing if a project doesn't provide a presubmit-tests
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS
