Repository tektoncd/experimental, pull requests merged in 2019-06, with the labels that each got.

#34 Link to getting started in tekton listener README
  tekton-listener/DEVELOPMENT.md
  tekton-listener/README.md
Labels: approved, lgtm, size/M

#52 Rough User Interface for Creating and Listing Webhooks
  .gitignore
  webhooks-extension/.babelrc
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/Gopkg.lock
  webhooks-extension/README.md
  webhooks-extension/build-it.sh
  webhooks-extension/cmd/extension/Dockerfile
  webhooks-extension/cmd/extension/kodata/extension.d78fd5a7.js
  webhooks-extension/cmd/extension/main.go
  webhooks-extension/cmd/sink/main.go
  webhooks-extension/config/extension-deployment.yaml
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/jest.config.js
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/pkg/endpoints/credentials.go
  webhooks-extension/pkg/endpoints/credentials_test.go
  webhooks-extension/pkg/endpoints/health.go
  webhooks-extension/pkg/endpoints/shared-test-funcs.go
  webhooks-extension/pkg/endpoints/sink.go
  webhooks-extension/pkg/endpoints/types.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/rollup.config.js
  webhooks-extension/src/WebhookApp.js
  webhooks-extension/src/api/comms.js
  webhooks-extension/src/api/index.js
  webhooks-extension/src/api/tests/comms.test.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
  webhooks-extension/src/components/WebhookCreate/index.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
  webhooks-extension/src/components/WebhookDisplayTable/index.js
  webhooks-extension/src/test/utils/test.js
  webhooks-extension/test-it.sh
  webhooks-extension/test/README.md
  webhooks-extension/test/util.sh
  webhooks-extension/test_config/__mocks__/fileMock.js
  webhooks-extension/test_config/__mocks__/styleMock.js
  webhooks-extension/test_config/setupTests.js
Labels: approved, lgtm, size/XXL

#71 SCSS fix for create button alignment.
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
Labels: approved, lgtm, size/S

#73 Refer to correct setShowNotificationOnTable function in tests
  webhooks-extension/package-lock.json
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
Labels: approved, lgtm, size/M

#81 Deletion of webhooks
  .gitignore
  webhooks-extension/build-it.sh
  webhooks-extension/cmd/extension/Dockerfile_test
  webhooks-extension/cmd/extension/kodata/extension.d78fd5a7.js
  webhooks-extension/cmd/sink/Dockerfile_test
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/redeploy.sh
  webhooks-extension/rollup.config.js
  webhooks-extension/src/api/comms.js
  webhooks-extension/src/api/index.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
  webhooks-extension/src/components/WebhookDisplayTable/StyledCheckbox.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteBasics.test.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js
Labels: approved, lgtm, size/XXL

#89 Change appearance and location of the add webhook button
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
Labels: approved, lgtm, size/L

#84 Add @mnuttall as root OWNER on experimental
  OWNERS
Labels: approved, lgtm, size/XS

#90 Fix issue with user supplying repo with .git suffix
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/M

#92 Fix issue with secret creation not auto selected (issue #80)
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
Labels: approved, lgtm, size/XS

#93 run eslint in the build
  webhooks-extension/.eslintignore
  webhooks-extension/.eslintrc.js
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/src/api/comms.js
  webhooks-extension/src/api/index.js
  webhooks-extension/src/api/tests/comms.test.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#99 Add script to publish experimental images
  tekton-listener/test/publish-images.sh
  test/publish-images.sh
  webhooks-extension/test/publish-images.sh
Labels: approved, lgtm, size/L

#100 publish-images.sh: use the correct path to call sub scripts 🤕
  test/publish-images.sh
Labels: approved, lgtm, size/XS

#101 publish-images.sh: use the real correct path to call sub scripts 🤕
  test/publish-images.sh
Labels: approved, lgtm, size/XS

#103 publish-images.sh: use pushd/popd and a loop to get in the right folder
  test/publish-images.sh
Labels: approved, lgtm, size/S

#105 Delete modal styling and implementation changes.
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/src/components/WebhookDisplayTable/StyledCheckbox.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteBasics.test.js
Labels: approved, lgtm, size/L

#106 publish-images.sh: don't fail on mkdir if the folder already exists
  tekton-listener/test/publish-images.sh
  webhooks-extension/test/publish-images.sh
Labels: approved, lgtm, size/XS

#108 Reset delete runs checkbox to be unchecked on dialog show, add test
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteDefaults.test.js
Labels: approved, lgtm, size/L

#107 Enable npm tests in prow on webhooks extension
  .gitignore
  webhooks-extension/package-lock.json
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
  webhooks-extension/test-it.sh
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#94 Update README with quickstart install instructions
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/README.md
  webhooks-extension/cmd/extension/Dockerfile
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/scripts/install_istio.sh
  webhooks-extension/scripts/install_knative.sh
  webhooks-extension/test/README.md
Labels: approved, lgtm, size/L, webhooks

#111 Remove dead code (deleteWebhook being registered twice)
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
Labels: approved, lgtm, size/S

#110 Install the extension release yaml in the tekton-pipelines namespace
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
Labels: approved, lgtm, size/XS

#112 Add bundle hash code test to ensure yaml matches npm build output
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#113 Use tekton-pipelines as namespace for test scripts and docs
  webhooks-extension/cmd/extension/README.md
  webhooks-extension/test/cleanup.sh
  webhooks-extension/test/config.sh
  webhooks-extension/test/setup_webhook_simple_test.sh
Labels: approved, lgtm, size/S

#116 Re-enable disabled webhook_tests
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/L
