Repository tektoncd/experimental, pull requests merged in 2019-11, with the labels that each got.

#316 Webhook Create Button Style Update
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
Labels: approved, lgtm, size/XS

#317 Border Correction for Firefox
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
Labels: approved, lgtm, size/XS

#315 Webhook names can contain '0'
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
Labels: approved, lgtm, size/XS

#318 Document test releases, and a small release code fix
  webhooks-extension/tekton/README.md
  webhooks-extension/tekton/publish.yaml
Labels: approved, lgtm, size/M

#320 Check OpenShift yaml under openshift folder too
  webhooks-extension/Gopkg.lock
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#274 Validating Secret in Webhook Create Page
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
Labels: approved, lgtm, size/M

#348 Use interceptor folder for nightly builds
  webhooks-extension/test/publish-images.sh
Labels: approved, lgtm, size/XS

#341 Make branch name available fo use in labels, also supply docs
  webhooks-extension/README.md
  webhooks-extension/cmd/interceptor/interceptor.go
  webhooks-extension/cmd/interceptor/interceptor_test.go
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/docs/GettingStarted.md
  webhooks-extension/docs/Labels.md
  webhooks-extension/docs/Parameters.md
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
  webhooks-extension/src/components/WebhookBranches/WebhookBranches.scss
  webhooks-extension/src/components/WebhookBranches/tests/WebhookBranches.test.js
Labels: approved, lgtm, size/L

#338 make monitor task timeout message configureable
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/monitor.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/docs/CustomizingTheMonitor.md
  webhooks-extension/docs/Monitoring.md
  webhooks-extension/pkg/endpoints/types.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/L

#299 Additional install script option to install nightly/release builds
  webhooks-extension/README.md
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/test/install_dashboard_and_extension.sh
  webhooks-extension/test/util.sh
Labels: approved, lgtm, size/L

#277 Remove Successfully Deleted Webhooks when Attempting to Delete Multiples
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/src/WebhookApp.test.js
  webhooks-extension/src/api/index.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js
Labels: approved, lgtm, size/L

#357 copy original .manifest files to output directory for pipeline 0.8
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/monitor.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
Labels: approved, lgtm, size/S

#356 Update to correct extension intereceptor image. Visible here: https:/…
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
Labels: approved, lgtm, size/XS

#347 handle ingress in go
  webhooks-extension/Gopkg.lock
  webhooks-extension/config/ingress-task.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/pkg/endpoints/webhook.go
Labels: approved, lgtm, size/L

#353 Format the branch name in the webhooks modal to be a clickable entity
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/docs/Labels.md
  webhooks-extension/docs/images/webhookBranches.png
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
  webhooks-extension/src/components/WebhookBranches/tests/WebhookBranches.test.js
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#351 Use go code to create/delete webhook
  webhooks-extension/Gopkg.lock
  webhooks-extension/config/github-webhook-task.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/pkg/endpoints/github.go
  webhooks-extension/pkg/endpoints/github_test.go
  webhooks-extension/pkg/endpoints/types.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/test/cleanup.sh
Labels: approved, lgtm, size/XXL

#354 check actions to process in the interceptor
  webhooks-extension/cmd/interceptor/interceptor.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/M

#364 Update href on help link and add serviceaccount to monitor
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/monitor.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
Labels: approved, lgtm, size/M

#366 Issue #363: Fix "No such file or directory" error for the .MANIFEST file during monitor
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/monitor.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
Labels: approved, lgtm, size/S

#369 Adds correct validation for webhook name length
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml
  webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml
  webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
Labels: approved, lgtm, size/S

#367 Release automation changes to include interceptor
  webhooks-extension/tekton/README.md
  webhooks-extension/tekton/publish.yaml
  webhooks-extension/tekton/release-pipeline.yml
  webhooks-extension/tekton/resources.yaml
Labels: approved, lgtm, size/S

#371 Remove the ConfigMap for webhooks
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/L

#373 Initialize the catalogs project.
  catalogs/OWNERS
  catalogs/cmd/catalogs/main.go
  catalogs/go.mod
  catalogs/go.sum
  catalogs/test/presubmit-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L
