Repository tektoncd/experimental, pull requests merged in 2019-07, with the labels that each got.

#109 tekton-listener does not need `npm` 👼
  tekton-listener/test/publish-images.sh
Labels: approved, lgtm, size/S

#129 Correct default install namespace to tekton-pipelines
  webhooks-extension/config/sink-kservice.yaml
Labels: approved, lgtm, size/XS

#126 Fix padding on webhooks modal button
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
Labels: approved, lgtm, size/S

#118 Update hash and WEB_RESOURCES_DIR for ko, remove Dockerfiles
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/cmd/extension/Dockerfile
  webhooks-extension/cmd/extension/Dockerfile_test
  webhooks-extension/cmd/sink/Dockerfile
  webhooks-extension/cmd/sink/Dockerfile_test
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#132 Show notification if no webhook selected for deletion.
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js
Labels: approved, lgtm, size/M

#122 Use namespace in request body for creating secrets
  webhooks-extension/cmd/extension/README.md
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/pkg/endpoints/credentials.go
  webhooks-extension/pkg/endpoints/credentials_test.go
  webhooks-extension/src/api/index.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
Labels: approved, lgtm, size/L

#135 Style the password invisible toggle on Webhooks secret create panel
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
Labels: approved, lgtm, size/S

#133 Update kube and tekton APIs to use proxy
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/src/api/index.js
  webhooks-extension/test_config/setupTests.js
Labels: approved, lgtm, size/M

#139 show notification when the last webhook deleted
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/WebhookApp.js
  webhooks-extension/src/WebhookApp.test.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js
Labels: approved, lgtm, size/L

#141 Adjust notifications to be consistent with main dashboard
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
Labels: approved, lgtm, size/M

#143 Update dev docs, no longer need to reinstall dash for extension pickup
  webhooks-extension/DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#144 Add branch to pipelinerun label from webhooks
  webhooks-extension/package-lock.json
  webhooks-extension/pkg/endpoints/sink.go
Labels: approved, lgtm, size/M

#149 data table skeleton when in loading state
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js
Labels: approved, lgtm, size/M

#157 Fix for vulnerability: https://www.npmjs.com/advisories/1013
  webhooks-extension/package-lock.json
Labels: approved, lgtm, size/M

#146 Add webhooks extension role, binding and SA
  webhooks-extension/config/extension-deployment.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
Labels: approved, lgtm, size/L, webhooks

#152 Multi-Namespace support for webhook pipelines
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/pkg/endpoints/credentials.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/src/api/index.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
Labels: approved, lgtm, size/L

#158 Increase privileges of dibbles to approver
  webhooks-extension/OWNERS
Labels: approved, lgtm, size/XS

#159 Secret token starred out in logs
  webhooks-extension/pkg/endpoints/credentials.go
  webhooks-extension/pkg/endpoints/credentials_test.go
Labels: approved, lgtm, size/XS

#148 filter webhooks by selected namespace
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/src/WebhookApp.js
  webhooks-extension/src/WebhookApp.test.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteBasics.test.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteDefaults.test.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js
Labels: approved, lgtm, size/L

#153 fix bug where after closing initial notification, the next ones were not appearing
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
Labels: approved, lgtm, size/S

#162 Replace 'npm install' with 'npm ci' for installing webhooks-extension
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/test/README.md
  webhooks-extension/test/util.sh
Labels: approved, lgtm, size/XS

#166 Fix PR unittest status by returning the result of the tests not an echo
  webhooks-extension/pkg/endpoints/credentials_test.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#168 Use defaults for namespace and fix skipping tests
  webhooks-extension/cmd/extension/README.md
  webhooks-extension/pkg/endpoints/credentials.go
  webhooks-extension/pkg/endpoints/credentials_test.go
  webhooks-extension/pkg/endpoints/shared-test-funcs.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/pkg/utils/utils_test.go
Labels: approved, lgtm, size/L

#161 Webhooks table batch action bar visible in safari (issue #128)
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/package-lock.json
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
Labels: approved, lgtm, size/M

#174 Add Megan Wright as reviewer for webhooks extension
  webhooks-extension/OWNERS
Labels: approved, lgtm, size/XS

#155 prevent tooltips from posting form
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
Labels: approved, lgtm, size/M

#169 replace api calls with dashboard's redux selectors & actions
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/WebhookApp.js
  webhooks-extension/src/WebhookApp.test.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalSecretName.test.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
Labels: approved, lgtm, size/XL

#173 Implement consistency across UI components for webhooks extension
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.scss
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.scss
Labels: approved, lgtm, size/M

#176 replace pipelines api call with dashboard's redux selectors & actions
  webhooks-extension/config/extension-service.yaml
  webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml
  webhooks-extension/src/WebhookApp.js
  webhooks-extension/src/WebhookApp.test.js
  webhooks-extension/src/components/WebhookCreate/WebhookCreate.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/CreateModalVisibilityAndToggle.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalCancel.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirm.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalConfirmError.test.js
  webhooks-extension/src/components/WebhookCreate/tests/DeleteModalSecretName.test.js
  webhooks-extension/src/components/WebhookCreate/tests/WebhookCreate.test.js
Labels: approved, lgtm, size/L

#175 Update readme with details on sink
  webhooks-extension/README.md
Labels: approved, lgtm, size/M

#178 Add OpenShift installation instructions including scc, route, cm settings
  webhooks-extension/README.md
Labels: approved, lgtm, size/M
