Repository tektoncd/experimental, pull requests merged in 2020-04, with the labels that each got.

#494 Add pipeline helm chart
  helm/OWNERS
  helm/README.md
  helm/pipeline/Chart.yaml
  helm/pipeline/README.md
  helm/pipeline/README.md.gotmpl
  helm/pipeline/crds/clustertask.yaml
  helm/pipeline/crds/condition.yaml
  helm/pipeline/crds/image.yaml
  helm/pipeline/crds/pipeline.yaml
  helm/pipeline/crds/pipelinerun.yaml
  helm/pipeline/crds/resource.yaml
  helm/pipeline/crds/task.yaml
  helm/pipeline/crds/taskrun.yaml
  helm/pipeline/templates/NOTES.txt
  helm/pipeline/templates/_helpers.tpl
  helm/pipeline/templates/clusterrole.yaml
  helm/pipeline/templates/clusterrolebinding.yaml
  helm/pipeline/templates/configmaps.yaml
  helm/pipeline/templates/controller_deployment.yaml
  helm/pipeline/templates/controller_service.yaml
  helm/pipeline/templates/customresourcedefinitions.yaml
  helm/pipeline/templates/podsecuritypolicy.yaml
  helm/pipeline/templates/serviceaccount.yaml
  helm/pipeline/templates/webhook_admission.yaml
  helm/pipeline/templates/webhook_deployment.yaml
  helm/pipeline/templates/webhook_poddisruptionbudget.yaml
  helm/pipeline/templates/webhook_service.yaml
  helm/pipeline/values-production.yaml
  helm/pipeline/values.yaml
  helm/repo-sync.sh
Labels: approved, lgtm, ok-to-test, size/XXL

#503 Tekton Triggers 0.4 support for webhooks extension
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/Gopkg.lock
  webhooks-extension/Gopkg.toml
  webhooks-extension/base/200-clusterrole-eventListener.yaml
  webhooks-extension/base/200-clusterrole.yaml
  webhooks-extension/base/200-role.yaml
  webhooks-extension/base/300-extension-service.yaml
  webhooks-extension/base/400-monitor-task.yaml
  webhooks-extension/base/400-monitor-triggerbinding.yaml
  webhooks-extension/base/400-monitor-triggertemplate.yaml
  webhooks-extension/docs/InstallPrereqs.md
  webhooks-extension/docs/Limitations.md
  webhooks-extension/docs/Parameters.md
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/src/api/index.js
  webhooks-extension/test/config.sh
Labels: approved, lgtm, size/XL

#506 Upgrade helm pipelines images to v0.11.1
  helm/pipeline/Chart.yaml
  helm/pipeline/README.md
  helm/pipeline/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#512 Use Triggers 0.4 (not a release candidate) in Gopkg yaml
  webhooks-extension/Gopkg.lock
  webhooks-extension/Gopkg.toml
Labels: approved, lgtm, size/XS

#510 Add script to check helm docs are up to date
  helm/.hack/check-helm-docs.sh
Labels: approved, lgtm, ok-to-test, size/S

#513 Add triggers helm chart
  helm/README.md
  helm/triggers/Chart.yaml
  helm/triggers/README.md
  helm/triggers/README.md.gotmpl
  helm/triggers/crds/clustertriggerbinding.yaml
  helm/triggers/crds/eventlistener.yaml
  helm/triggers/crds/triggerbinding.yaml
  helm/triggers/crds/triggertemplate.yaml
  helm/triggers/templates/NOTES.txt
  helm/triggers/templates/_helpers.tpl
  helm/triggers/templates/clusterrole.yaml
  helm/triggers/templates/clusterrolebinding.yaml
  helm/triggers/templates/configmaps.yaml
  helm/triggers/templates/controller_deployment.yaml
  helm/triggers/templates/controller_service.yaml
  helm/triggers/templates/customresourcedefinitions.yaml
  helm/triggers/templates/podsecuritypolicy.yaml
  helm/triggers/templates/serviceaccount.yaml
  helm/triggers/templates/webhook_admission.yaml
  helm/triggers/templates/webhook_deployment.yaml
  helm/triggers/templates/webhook_poddisruptionbudget.yaml
  helm/triggers/templates/webhook_service.yaml
  helm/triggers/values-production.yaml
  helm/triggers/values.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#511 Helm charts versioning
  helm/README.md
  helm/dashboard/Chart.yaml
  helm/dashboard/README.md
  helm/pipeline/Chart.yaml
  helm/pipeline/README.md
Labels: approved, lgtm, ok-to-test, size/S

#515 Add icons in charts description
  helm/dashboard/Chart.yaml
  helm/pipeline/Chart.yaml
  helm/triggers/Chart.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#519 Add skeleton of Results API service and watcher
  results/README.md
  results/cmd/api/main.go
  results/cmd/watcher/main.go
  results/config/api.yaml
  results/config/watcher.yaml
  results/go.mod
  results/go.sum
  results/proto/api.proto
  results/proto/doc.go
  results/proto/proto/api.pb.go
Labels: approved, lgtm, size/XXL

#508 Update webhooks release pipeline to use v1beta1 resources
  webhooks-extension/tekton/build.yml
  webhooks-extension/tekton/publish.yaml
  webhooks-extension/tekton/resources.yaml
Labels: approved, lgtm, size/M

#518 Add script to check chart version is incremented when a chart is modified
  helm/.hack/check-helm-docs.sh
  helm/.hack/check-version.sh
Labels: approved, lgtm, size/M

#524 Fix helm chart changes not detected
  helm/.hack/check-version.sh
Labels: approved, lgtm, size/S

#527 Dashboard chart v0.6.1 and ingress support
  helm/dashboard/Chart.yaml
  helm/dashboard/README.md
  helm/dashboard/templates/dashboard_ingress.yaml
  helm/dashboard/templates/dashboard_pipeline.yaml
  helm/dashboard/templates/dashboard_task.yaml
  helm/dashboard/values.yaml
Labels: approved, lgtm, size/L
