Repository tektoncd/experimental, pull requests merged in 2020-09, with the labels that each got.

#627 Hub: replace default logger in gorm with suggared logger
  hub/api/pkg/app/app.go
Labels: approved, lgtm, size/S

#629 Hub: use sha256 instead of tags
  hub/api/config/12-db-deployment.yaml
Labels: approved, lgtm, size/XS

#631 results: Simplify Tekton->proto conversion.
  results/pkg/convert/convert.go
  results/pkg/convert/convert_test.go
  results/proto/doc.go
  results/proto/proto/api.pb.go
  results/proto/proto/api_grpc.pb.go
  results/proto/proto/taskrun.pb.go
  results/proto/taskrun.proto
Labels: approved, lgtm, size/XL

#632 Results - use new TaskRun neutral API.
  results/cmd/api/results.sql
  results/cmd/watcher/controller.go
  results/cmd/watcher/main.go
  results/cmd/watcher/main_test.go
  results/go.sum
  results/pkg/server/server.go
  results/pkg/server/server_test.go
  results/proto/api.proto
  results/proto/proto/api.pb.go
  results/proto/proto/api_grpc.pb.go
  results/proto/proto/taskrun.pb.go
  results/proto/taskrun.proto
Labels: approved, lgtm, size/XXL

#633 Results: Add .gitattributes file.
  results/.gitattributes
Labels: approved, lgtm, size/XS

#630 Hub: Modifies ui-new based on changes in upstream api response
  hub/ui-new/src/components/Authentication/Login.tsx
  hub/ui-new/src/components/assets/logo/main.png
  hub/ui-new/src/components/basic-detail/BasicDetail.tsx
  hub/ui-new/src/components/filter/Filter.tsx
  hub/ui-new/src/components/filter/Sort.tsx
  hub/ui-new/src/components/main/App.tsx
  hub/ui-new/src/components/rating/Rating.tsx
  hub/ui-new/src/components/redux/Actions/TaskActionDescription.tsx
  hub/ui-new/src/components/search-bar/SearchBar.tsx
  hub/ui-new/src/components/task/Task.tsx
  hub/ui-new/src/components/task/index.css
Labels: approved, lgtm, size/L
