Repository tektoncd/experimental, pull requests merged in 2020-02, with the labels that each got.

#449 Change build script to look for directories instead of files
  webhooks-extension/build-it.sh
Labels: approved, lgtm, size/S

#418 tekdoc :: parse input file to yaml
  tekdoc/go.mod
  tekdoc/go.sum
  tekdoc/main.go
Labels: approved, lgtm, ok-to-test, size/M

#453 Updates webhooks extension eventlistener to be compatible with triggers 0.2.1
  webhooks-extension/Gopkg.lock
  webhooks-extension/Gopkg.toml
  webhooks-extension/base/200-clusterrole-eventListener.yaml
  webhooks-extension/cmd/interceptor/interceptor.go
  webhooks-extension/cmd/interceptor/utils_test.go
  webhooks-extension/docs/InstallPrereqs.md
  webhooks-extension/pkg/endpoints/credentials.go
  webhooks-extension/pkg/endpoints/shared-test-funcs.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/pkg/utils/utils.go
Labels: approved, lgtm, size/XXL

#370 TLS certificate is added to the ingress for the eventlistener
  webhooks-extension/Gopkg.lock
  webhooks-extension/docs/InstallNightlyBuild.md
  webhooks-extension/docs/InstallReleaseBuild.md
  webhooks-extension/pkg/endpoints/webhook.go
Labels: approved, lgtm, size/L

#462 Fix gitlab interceptor URL check
  webhooks-extension/cmd/interceptor/gitlab.go
Labels: approved, lgtm, size/S

#466 Use go-containerregistry to parse image references
  oci/go.mod
  oci/pkg/action/pull.go
  oci/pkg/action/push.go
  oci/pkg/oci/image.go
Labels: approved, lgtm, size/L

#467 Ignore empty content when decoding
  oci/pkg/oci/bundle.go
Labels: approved, lgtm, size/XS

#469 Use npm run build_ko in DEVELOPMENT instructions
  webhooks-extension/DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#468 Use go-containerregistry to push and pull
  oci/go.mod
  oci/go.sum
  oci/pkg/oci/image.go
Labels: approved, lgtm, size/L

#477 OCI: minor code cleanup
  oci/pkg/action/pull.go
  oci/pkg/oci/bundle.go
  oci/pkg/oci/image.go
Labels: approved, lgtm, size/M

#473 Install yq in build pipeline
  webhooks-extension/tekton/build.yml
Labels: approved, lgtm, size/XS
