Repository tektoncd/experimental, pull requests merged in 2020-08, with the labels that each got.

#617 Hub: modifies homepage UI and resource detail page
  hub/ui-new/src/components/basic-detail/BasicDetail.tsx
  hub/ui-new/src/components/main/App.tsx
  hub/ui-new/src/components/rating/Rating.tsx
  hub/ui/src/components/basic-detail/BasicDetail.tsx
  hub/ui/src/components/main/App.tsx
  hub/ui/src/components/rating/Rating.tsx
Labels: approved, lgtm, size/XL

#619 Hub: Updates cronjob to run sync every 30 min
  hub/api/config/db-migration/15-db-cronjob.yaml
Labels: approved, lgtm, size/XS

#620 Hub: Fixes trailing spaces in api response
  hub/api/pkg/service/category.go
  hub/api/pkg/service/resource.go
Labels: approved, lgtm, size/XS

#615 Change return type of ListTaskRunsResult
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/proto/api.proto
  results/proto/proto/api.pb.go
Labels: approved, lgtm, size/L

#621 Hub: Fixes trailing spaces in api
  hub/api/pkg/git/repo.go
  hub/api/pkg/service/category.go
  hub/api/pkg/service/resource.go
Labels: approved, lgtm, size/S

#609 Add update to watcher and results_id to annotation field of taskrun
  results/cmd/api/main.go
  results/cmd/watcher/controller.go
  results/cmd/watcher/main.go
  results/cmd/watcher/main_test.go
  results/go.mod
  results/go.sum
  results/pkg/server/server.go
  results/pkg/server/server_test.go
Labels: approved, lgtm, size/XL

#623 Use the go-scm DriverIdentification mechanism to create clients.
  commit-status-tracker/README.md
  commit-status-tracker/cmd/manager/main.go
  commit-status-tracker/go.mod
  commit-status-tracker/go.sum
  commit-status-tracker/pkg/controller/pipelinerun/client.go
  commit-status-tracker/pkg/controller/pipelinerun/client_test.go
  commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller.go
  commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller_test.go
Labels: approved, lgtm, size/XL

#625 Update webhooks-extension docs to reference last release - v0.7.0
  webhooks-extension/docs/InstallReleaseBuild.md
Labels: approved, lgtm, size/M
