Repository tektoncd/experimental, pull requests merged in 2020-07, with the labels that each got.

#574 Hub: Fix prod-doc for sync db step
  hub/docs/prod-deployment.md
Labels: approved, lgtm, size/S

#583 Hub:Replace Red Hat copyright with tekton.dev copyright
  hub/ui/src/components/footer/Footer.tsx
Labels: approved, lgtm, size/L

#560 Get task from database v1
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/cmd/api/results.sql
  results/go.sum
Labels: approved, lgtm, size/L

#584 Hub:Resizes CD foundation logo in footer
  hub/ui/src/components/footer/Footer.tsx
Labels: approved, lgtm, size/XS

#585 Hub: Google/ko 5.0+ requires images to be prefixed by ko://
  hub/api/config/21-api-deployment.yaml
  hub/api/config/db-migration/14-db-migration.yaml
Labels: approved, lgtm, size/XS

#586 Hub: use tekton specific annotations for tags and displayName
  hub/api/pkg/git/repo.go
Labels: approved, lgtm, size/XS

#562 Update task version 1
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/cmd/watcher/main.go
  results/go.mod
  results/go.sum
Labels: approved, lgtm, size/M

#561 Delete taskrun version 1
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/proto/api.proto
  results/proto/proto/api.pb.go
Labels: approved, lgtm, size/L

#588 Implement adding results_id to schema v1
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/cmd/watcher/main.go
  results/go.mod
  results/proto/api.proto
  results/proto/proto/api.pb.go
Labels: approved, lgtm, size/L

#582 Add support for applying and deleting configs on cluster
  generators/cmd/cli/cmd/root.go
  generators/pkg/manager/manage.go
  generators/pkg/manager/manage_test.go
Labels: approved, lgtm, size/L

#591 Hub: switch to upstream catalog
  hub/api/pkg/db/model/migration.go
Labels: approved, lgtm, size/XS

#590 Add apply and delete sub-commands to generators cli
  generators/cmd/cli/cmd/apply.go
  generators/cmd/cli/cmd/delete.go
Labels: approved, lgtm, size/M

#589 Implement watcher to connect it to cluster and api server
  results/cmd/api/.gitignore
  results/cmd/api/results.sql
  results/cmd/watcher/main.go
  results/go.sum
Labels: approved, lgtm, size/M

#572 Results: Read test DB schema from file.
  results/README.md
  results/cmd/api/main_test.go
  results/cmd/api/results.sql
  results/go.sum
Labels: approved, lgtm, size/M

#593 Add fieldmask utility to UpdateTaskRun to only update specific fields
  results/.gitignore
  results/cmd/api/.gitignore
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/go.mod
  results/go.sum
  results/proto/api.proto
  results/proto/proto/api.pb.go
Labels: approved, lgtm, size/XL

#602 Hub: Add support for pipeline in sync service
  hub/api/pkg/git/repo.go
Labels: approved, lgtm, size/S

#604 Hub: Add cronjob to sync catalog changes to db at regular interval
  hub/api/config/db-migration/15-db-cronjob.yaml
Labels: approved, lgtm, size/S

#595 Hub: Fixes summary of a resource on the resource card
  hub/ui/src/components/task/Task.tsx
  hub/ui/src/components/task/index.css
Labels: approved, lgtm, size/M

#605 Move existing CLI commands to trigger subcommand.
  generators/cmd/cli/cmd/apply.go
  generators/cmd/cli/cmd/delete.go
  generators/cmd/cli/cmd/root.go
  generators/cmd/cli/cmd/trigger/apply.go
  generators/cmd/cli/cmd/trigger/delete.go
  generators/cmd/cli/cmd/trigger/show.go
  generators/cmd/cli/cmd/trigger/trigger.go
  generators/cmd/cli/cmd/trigger/write.go
Labels: approved, lgtm, size/L

#607 Hub: adds tooltip for badges and font for resource name
  hub/ui-new/.eslintrc
  hub/ui-new/src/components/basic-detail/BasicDetail.tsx
  hub/ui-new/src/components/filter/Filter.tsx
  hub/ui-new/src/components/task/Task.tsx
  hub/ui/src/components/basic-detail/BasicDetail.tsx
  hub/ui/src/components/filter/Filter.tsx
  hub/ui/src/components/task/Task.tsx
Labels: approved, lgtm, size/L

#608 Hub: fixes scroll position
  hub/ui-new/src/components/main/App.tsx
  hub/ui/src/components/main/App.tsx
Labels: approved, lgtm, size/XS

#603 Modifies Markdown rendering on detail page
  hub/ui-new/src/components/description/CodeBlockReadme.tsx
  hub/ui-new/src/components/description/Description.tsx
  hub/ui-new/src/components/description/index.css
  hub/ui-new/src/components/rating/index.css
  hub/ui/src/components/description/CodeBlockReadme.tsx
  hub/ui/src/components/description/Description.tsx
  hub/ui/src/components/description/index.css
  hub/ui/src/components/rating/index.css
Labels: approved, lgtm, size/M

#606 Aligns Task detail background to center
  hub/ui-new/src/components/description/Description.tsx
  hub/ui-new/src/components/detail/Detail.tsx
  hub/ui/src/components/description/Description.tsx
  hub/ui/src/components/detail/Detail.tsx
Labels: approved, lgtm, size/S

#610 Hub: Modifies the rating icons on detail page
  hub/ui-new/src/components/rating/Rating.tsx
  hub/ui-new/src/components/rating/index.css
  hub/ui/src/components/rating/Rating.tsx
  hub/ui/src/components/rating/index.css
Labels: approved, lgtm, size/L

#612 Merge the content of design doc to the README for Tekton Generators
  generators/README.md
Labels: approved, lgtm, size/M

#599 Implement query API of Tekton Results API
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/go.mod
  results/go.sum
  results/proto/api.proto
  results/proto/proto/api.pb.go
Labels: approved, lgtm, size/L
