Repository tektoncd/experimental, pull requests merged in 2020-05, with the labels that each got.

#534 Add pkg/convert to translate Go structs to proto messages
  results/cmd/api/main.go
  results/cmd/watcher/main.go
  results/go.mod
  results/go.sum
  results/pkg/convert/convert.go
  results/pkg/convert/convert_test.go
  results/proto/api.proto
  results/proto/doc.go
  results/proto/proto/api.pb.go
  results/proto/proto/taskrun.pb.go
  results/proto/taskrun.proto
Labels: approved, lgtm, size/XXL

#530 Bump plumbing to recent master 👼
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#541 Delete flaky test: WebhookDeleteNotifications
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookDeleteNotifications.test.js
Labels: approved, lgtm, size/L

#531 [webhooks-extension] add recommended k8s labels
  webhooks-extension/base/200-clusterrole-eventListener.yaml
  webhooks-extension/base/200-clusterrole.yaml
  webhooks-extension/base/200-role.yaml
  webhooks-extension/base/200-serviceaccount-eventListener.yaml
  webhooks-extension/base/200-serviceaccount.yaml
  webhooks-extension/base/201-clusterrolebinding-eventListener.yaml
  webhooks-extension/base/201-clusterrolebinding.yaml
  webhooks-extension/base/201-rolebinding.yaml
  webhooks-extension/base/300-extension-deployment.yaml
  webhooks-extension/base/300-extension-service.yaml
  webhooks-extension/base/300-interceptor-deployment.yaml
  webhooks-extension/base/300-interceptor-service.yaml
  webhooks-extension/base/400-monitor-task.yaml
  webhooks-extension/base/400-monitor-triggerbinding.yaml
  webhooks-extension/base/400-monitor-triggertemplate.yaml
  webhooks-extension/overlays/openshift-all/deployment-patch.yaml
  webhooks-extension/overlays/plainkube-all/deployment-patch.yaml
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/test/dashboard-service.yaml
Labels: approved, lgtm, size/L

#542 webhooks-extension: Add support for CSRF token
  webhooks-extension/base/300-extension-service.yaml
  webhooks-extension/src/api/comms.js
  webhooks-extension/src/api/index.js
  webhooks-extension/src/api/tests/comms.test.js
  webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
  webhooks-extension/src/test/utils/test.js
Labels: approved, lgtm, size/M

#543 Document + use in test new nginx install method
  webhooks-extension/docs/InstallPrereqs.md
  webhooks-extension/test/util.sh
Labels: approved, lgtm, size/XS

#537 [helm/dashboard] Fix triggers api group in RBAC
  helm/dashboard/Chart.yaml
  helm/dashboard/README.md
  helm/dashboard/templates/clusterrole.yaml
Labels: approved, lgtm, size/S

#546 Install webhooks extension on openshift to openshift-pipelines, matching Dashboard
  webhooks-extension/overlays/openshift-all/kustomization.yaml
Labels: approved, lgtm, size/XS

#549 Add Triggers 0.5.0 support for webhooks extension
  webhooks-extension/README.md
  webhooks-extension/base/400-monitor-triggertemplate.yaml
Labels: approved, lgtm

#550 update other kubernetes enviroments install yaml name
  webhooks-extension/docs/InstallReleaseBuild.md
Labels: approved, lgtm, size/XS
