Repository tektoncd/experimental, pull requests merged in 2020-01, with the labels that each got.

#408 Handle missing PipelineRuns for monitor task
  webhooks-extension/base/400-monitor-task.yaml
  webhooks-extension/base/400-monitor-triggertemplate.yaml
  webhooks-extension/docs/CustomizingTheMonitor.md
  webhooks-extension/pkg/endpoints/types.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/L

#424 Add service account column to webhooks display table
  webhooks-extension/base/300-extension-service.yaml
  webhooks-extension/src/components/WebhookBranches/WebhookBranches.js
  webhooks-extension/src/components/WebhookDisplayTable/WebhookDisplayTable.js
  webhooks-extension/src/components/WebhookDisplayTable/tests/WebhookTable.test.js
Labels: approved, lgtm, size/S

#423 Update webhooks doc for 0.3.0 release
  webhooks-extension/README.md
  webhooks-extension/docs/InstallNightlyBuild.md
  webhooks-extension/docs/InstallPrereqs.md
  webhooks-extension/docs/InstallReleaseBuild.md
Labels: approved, lgtm, size/S

#409 Update with EKS environment information
  webhooks-extension/docs/GettingStarted.md
  webhooks-extension/docs/InstallNightlyBuild.md
  webhooks-extension/docs/InstallReleaseBuild.md
Labels: approved, lgtm, size/M

#427 make https for default protocol for webhook in OpenShift
  webhooks-extension/overlays/openshift-all/deployment-patch.yaml
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/S

#428 Add OpenShift registry URL for 3.11
  webhooks-extension/docs/NotesOnOpenShiftInstallations.md
Labels: approved, lgtm, size/XS

#434 Add support for using gitlab as a git provider.
  webhooks-extension/Gopkg.lock
  webhooks-extension/README.md
  webhooks-extension/base/400-monitor-task.yaml
  webhooks-extension/base/400-monitor-triggerbinding.yaml
  webhooks-extension/base/400-monitor-triggertemplate.yaml
  webhooks-extension/cmd/interceptor/github.go
  webhooks-extension/cmd/interceptor/gitlab.go
  webhooks-extension/cmd/interceptor/interceptor.go
  webhooks-extension/cmd/interceptor/interceptor_test.go
  webhooks-extension/cmd/interceptor/utils.go
  webhooks-extension/cmd/interceptor/utils_test.go
  webhooks-extension/docs/Architecture.md
  webhooks-extension/docs/GettingStarted.md
  webhooks-extension/docs/Limitations.md
  webhooks-extension/docs/Monitoring.md
  webhooks-extension/docs/MultiplePipelines.md
  webhooks-extension/docs/Parameters.md
  webhooks-extension/docs/Security.md
  webhooks-extension/docs/WebhookSecurity.md
  webhooks-extension/pkg/endpoints/git.go
  webhooks-extension/pkg/endpoints/github.go
  webhooks-extension/pkg/endpoints/gitlab.go
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
  webhooks-extension/pkg/utils/utils.go
Labels: approved, lgtm, size/XXL

#443 Don't pass the PullRequest if no PipelineRuns ever found for it
  webhooks-extension/base/400-monitor-task.yaml
Labels: approved, lgtm, size/S

#444 Update uninstall docs to include created route/ingress
  webhooks-extension/docs/Uninstall.md
Labels: approved, lgtm, size/S

#445 Automatically use the generated hash for your service yaml
  webhooks-extension/DEVELOPMENT.md
  webhooks-extension/build-it.sh
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/test/presubmit-tests.sh
Labels: approved, lgtm, size/M
