Repository tektoncd/experimental, pull requests merged in 2020-10, with the labels that each got.

#634 Results: Configure API Server and Watcher to run against remote servers.
  results/cmd/api/README.md
  results/cmd/api/main.go
  results/cmd/api/results.sql
  results/cmd/watcher/main.go
  results/go.mod
  results/go.sum
  results/pkg/grpc/creds.go
  results/pkg/grpc/doc.go
  results/pkg/server/server.go
  results/schema/results.sql
Labels: approved, lgtm, size/L

#639 Hub: Fix console error for rating API
  hub/ui/src/components/rating/Rating.tsx
Labels: approved, lgtm, size/S

#640 Hub: Modifies header height
  hub/ui/src/components/background-image/image.css
  hub/ui/src/components/rating/Rating.tsx
Labels: approved, lgtm, size/S

#643 Results: Fix k8s service yaml for on-cluster support.
  results/README.md
  results/cmd/watcher/main.go
  results/config/api.yaml
  results/config/watcher.yaml
Labels: approved, lgtm, size/M

#642 Hub: Add hub token copy feature
  hub/ui/src/components/main/App.tsx
  hub/ui/src/components/main/index.css
Labels: approved, lgtm, size/M

#648 Results: refactor api/watcher packages into separate pkg subfolders.
  results/cmd/api/main.go
  results/cmd/watcher/controller.go
  results/cmd/watcher/main.go
  results/go.mod
  results/pkg/api/server/server.go
  results/pkg/api/server/server_test.go
  results/pkg/watcher/convert/convert.go
  results/pkg/watcher/convert/convert_test.go
  results/pkg/watcher/grpc/creds.go
  results/pkg/watcher/grpc/doc.go
  results/pkg/watcher/reconciler/controller.go
  results/pkg/watcher/reconciler/controller_test.go
Labels: approved, lgtm, size/L

#650 Update the OCI experimental tool to match the current Tekton bundle f…
  oci/go.mod
  oci/go.sum
  oci/pkg/oci/bundle.go
  oci/pkg/oci/image.go
Labels: approved, lgtm, ok-to-test, size/M

#653 Hub: Updates UI according to changes in API response
  hub/ui/src/components/filter/Filter.tsx
  hub/ui/src/components/redux/Actions/ResourcesList.tsx
  hub/ui/src/components/redux/Actions/TaskAction.tsx
  hub/ui/src/components/redux/Actions/TaskDataListAction.tsx
Labels: approved, lgtm, size/S

#655 Hub: Updates UI acc to changes in API response for list of versions
  hub/ui/src/components/basic-detail/BasicDetail.tsx
  hub/ui/src/components/basic-detail/BasicDetailParent.tsx
  hub/ui/src/components/redux/Actions/TaskActionName.tsx
Labels: approved, lgtm, size/S

#626 Using CronJobs to automatically clean up completed Runs
  pipeline/cleanup/README.md
  pipeline/cleanup/binding.yaml
  pipeline/cleanup/cleanup-template.yaml
  pipeline/cleanup/cronjob.yaml
  pipeline/cleanup/eventlistener.yaml
  pipeline/cleanup/serviceaccount.yaml
Labels: approved, lgtm, size/L

#656 Add Jason and Andrea to owners
  OWNERS
Labels: approved, lgtm, size/XS

#658 [experimental] Add project tag for commit in the PR template
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#649 Update presubmit-tests scripts to include task-loops
  task-loops/test/e2e-common.sh
  task-loops/test/e2e-taskloops.sh
  task-loops/test/e2e-tests.sh
  task-loops/test/presubmit-tests.sh
  task-loops/test/tasklooprun_test.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#657 [OCI] Drop the vendor mode in the OCI tool makefile
  oci/Makefile
Labels: approved, lgtm, size/S

#665 Fix SDK bug and update SDK examples
  sdk/python/examples/taskrun.ipynb
  sdk/python/setup.py
  sdk/python/tekton/api/tekton_client.py
  sdk/python/tekton/models/v1beta1_when_expression.py
Labels: approved, lgtm, size/M
