Repository tektoncd/experimental, pull requests merged in 2020-06, with the labels that each got.

#553 Fix wrong namespace for monitor TaskRun on OpenShift
  webhooks-extension/base/400-monitor-triggertemplate.yaml
Labels: approved, lgtm, size/XS

#551 [Webhooks] Always use Dashboard service
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/S

#554 Remove inactive users from reviewers list
  webhooks-extension/OWNERS
Labels: approved, lgtm, size/XS

#558 Create CLI tool based on Tekton Generators
  generators/OWNERS
  generators/README.md
  generators/cmd/main.go
  generators/go.mod
  generators/go.sum
  generators/pkg/generator/generate.go
  generators/pkg/generator/generate_test.go
  generators/pkg/parser/parser.go
  generators/pkg/parser/parser_test.go
  generators/pkg/parser/testdata/products.yaml
Labels: approved, lgtm, size/XXL

#568 Update to v1beta1
  commit-status-tracker/README.md
  commit-status-tracker/cmd/manager/main.go
  commit-status-tracker/docs/examples/pipeline.yaml
  commit-status-tracker/docs/examples/pipeline_run_with_git.yaml
  commit-status-tracker/docs/examples/test_task.yaml
  commit-status-tracker/go.mod
  commit-status-tracker/go.sum
  commit-status-tracker/pkg/controller/pipelinerun/commit_status_input.go
  commit-status-tracker/pkg/controller/pipelinerun/commit_status_input_test.go
  commit-status-tracker/pkg/controller/pipelinerun/notifiable.go
  commit-status-tracker/pkg/controller/pipelinerun/notifiable_test.go
  commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller.go
  commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller_test.go
  commit-status-tracker/pkg/controller/pipelinerun/resource.go
  commit-status-tracker/pkg/controller/pipelinerun/resource_test.go
  commit-status-tracker/pkg/controller/pipelinerun/run_state.go
  commit-status-tracker/pkg/controller/pipelinerun/run_state_test.go
  commit-status-tracker/test/builder/builder.go
Labels: approved, lgtm, size/XXL

#565 Make webhooks work with triggers master
  webhooks-extension/Gopkg.lock
  webhooks-extension/Gopkg.toml
  webhooks-extension/package-lock.json
  webhooks-extension/package.json
  webhooks-extension/pkg/endpoints/webhook.go
  webhooks-extension/pkg/endpoints/webhook_test.go
Labels: approved, lgtm, size/L

#563 Add results/OWNERS
  results/OWNERS
Labels: approved, lgtm, size/S

#571 Hub: Adds doc stating steps to deploy to production
  hub/docs/prod-deployment.md
Labels: approved, lgtm, size/L

#559 Implement CREATE functon of taskrun CRUD Version 1
  results/README.md
  results/cmd/api/main.go
  results/cmd/api/main_test.go
  results/cmd/api/results.sql
  results/go.mod
  results/go.sum
  results/proto/api.proto
  results/proto/proto/api.pb.go
  results/proto/proto/taskrun.pb.go
Labels: approved, lgtm, size/XL

#564 Add CLI and Write support to Tekton Generators
  generators/cmd/cli/cmd/root.go
  generators/cmd/cli/cmd/show.go
  generators/cmd/cli/cmd/write.go
  generators/cmd/main.go
  generators/go.mod
  generators/go.sum
  generators/pkg/generator/generate.go
  generators/pkg/generator/generate_test.go
  generators/pkg/parser/parser.go
  generators/pkg/parser/parser_test.go
  generators/pkg/parser/testdata/spec-full.yaml
  generators/pkg/parser/testdata/spec.yaml
  generators/pkg/writer/testdata/spec.yaml
  generators/pkg/writer/testdata/task.yaml
  generators/pkg/writer/write.go
  generators/pkg/writer/write_test.go
Labels: approved, lgtm, size/L

#573 Modifies README.md and adds deployed application link
  hub/README.md
Labels: approved, lgtm, size/S

#539 Connect to a local MySQL instance to store results
  results/README.md
  results/cmd/api/main.go
  results/cmd/watcher/main.go
  results/config/api.yaml
  results/config/db.yaml
  results/go.mod
  results/go.sum
Labels: approved, lgtm, size/L

#579 Revert "Connect to a local MySQL instance to store results"
  results/README.md
  results/cmd/api/main.go
  results/cmd/watcher/main.go
  results/config/api.yaml
  results/config/db.yaml
  results/go.mod
  results/go.sum
Labels: approved, lgtm, size/L

#578 Add results and generators to presubmit-test.sh.
  generators/test/presubmit-tests.sh
  results/go.mod
  results/go.sum
  results/test/presubmit-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L
