Repository tektoncd/experimental, pull requests merged in 2020-11, with the labels that each got.

#635 Support configurable secret names.
  commit-status-tracker/README.md
  commit-status-tracker/pkg/controller/pipelinerun/pipelinerun_controller_test.go
  commit-status-tracker/pkg/controller/pipelinerun/secret.go
  commit-status-tracker/pkg/controller/pipelinerun/secret_test.go
Labels: approved, lgtm, size/M

#664 Introduce customized scheduler to resolve issues from tekton
  scheduler/.ko.yaml
  scheduler/OWNERS
  scheduler/README.md
  scheduler/cmd/main.go
  scheduler/config/100-serviceaccount.yaml
  scheduler/config/101-clusterrole.yaml
  scheduler/config/102-clusterrolebinding.yaml
  scheduler/config/201-configmap.yaml
  scheduler/config/500-deployment.yaml
  scheduler/example/pods.yaml
  scheduler/go.mod
  scheduler/go.sum
  scheduler/pkg/coscheduler/coscheduler.go
  scheduler/pkg/coscheduler/coscheduler_test.go
Labels: approved, lgtm, size/XXL

#667 [SDK] Enhance SDK API and update examples
  sdk/python/README.md
  sdk/python/docs/TektonClient.md
  sdk/python/examples/taskrun.ipynb
  sdk/python/examples/tekton_pipeline_python_sdk_sample.ipynb
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tekton_pipeline/api/tekton_client.py
  sdk/python/tekton_pipeline/api/tekton_watch.py
  sdk/python/tekton_pipeline/utils/utils.py
Labels: approved, lgtm, size/XXL

#668 [results] Add e2e tests.
  results/README.md
  results/cmd/watcher/main.go
  results/config/101-mysql-deployment.yaml
  results/config/api.yaml
  results/test/e2e/README.md
  results/test/e2e/install.sh
  results/test/e2e/setup.sh
  results/test/e2e/taskrun.yaml
  results/test/e2e/test.sh
Labels: approved, lgtm, size/L

#661 [results] Move proto definitions into separate versioned folders.
  results/cmd/api/main.go
  results/cmd/watcher/main.go
  results/go.sum
  results/pkg/api/server/server.go
  results/pkg/api/server/server_test.go
  results/pkg/watcher/convert/convert.go
  results/pkg/watcher/convert/convert_test.go
  results/pkg/watcher/reconciler/internal/common.go
  results/pkg/watcher/reconciler/pipelinerun/controller.go
  results/pkg/watcher/reconciler/pipelinerun/pipelinerun.go
  results/pkg/watcher/reconciler/pipelinerun/pipelinerun_test.go
  results/pkg/watcher/reconciler/reconciler_test.go
  results/pkg/watcher/reconciler/taskrun/controller.go
  results/pkg/watcher/reconciler/taskrun/taskrun.go
  results/pkg/watcher/reconciler/taskrun/taskrun_test.go
  results/proto/doc.go
  results/proto/pipeline/v1beta1/common.proto
  results/proto/pipeline/v1beta1/generate.go
  results/proto/pipeline/v1beta1/pipeline_go_proto/common.pb.go
  results/proto/pipeline/v1beta1/pipeline_go_proto/pipelinerun.pb.go
  results/proto/pipeline/v1beta1/pipeline_go_proto/taskrun.pb.go
  results/proto/pipeline/v1beta1/pipelinerun.proto
  results/proto/pipeline/v1beta1/taskrun.proto
  results/proto/v1alpha1/api.proto
  results/proto/v1alpha1/generate.go
  results/proto/v1alpha1/results_go_proto/api.pb.go
  results/proto/v1alpha1/results_go_proto/api_grpc.pb.go
Labels: approved, lgtm, size/XXL

#671 [results] Supports to Filter PipelineRun in List API
  results/pkg/api/server/server.go
  results/pkg/api/server/server_test.go
Labels: approved, lgtm, size/L
