Repository tektoncd/experimental, pull requests merged in 2022-03, with the labels that each got.

#836 [workflows] Add @savitaashture as an approver
  workflows/OWNERS
Labels: size/XS, approved, lgtm

#838 [pipeline/trusted-resources] Add OWNERS file.
  pipeline/trusted-resources/OWNERS
  test/presubmit-tests.sh
Labels: size/S, approved, lgtm

#833 [TrustTask] Trusted taskspec verification
  pipeline/trusted-resources/.gitignore
  pipeline/trusted-resources/LICENSE
  pipeline/trusted-resources/README.md
  pipeline/trusted-resources/go.mod
  pipeline/trusted-resources/go.sum
  pipeline/trusted-resources/hack/boilerplate/boilerplate.go.txt
  pipeline/trusted-resources/pkg/trustedtask/doc.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
  pipeline/trusted-resources/pkg/trustedtask/zz_generated.deepcopy.go
  pipeline/trusted-resources/tools/go.mod
  pipeline/trusted-resources/tools/go.sum
  pipeline/trusted-resources/tools/tools.go
Labels: approved, lgtm, size/XXL

#843 [cloudevents] Tweak nightly build resources
  cloudevents/tekton/release-pipeline.yaml
Labels: size/XS, approved, lgtm

#845 [cloudevents] Fix the publish task to make creds discoverable
  cloudevents/tekton/publish.yaml
Labels: size/XS, approved, lgtm

#844 [cloudevents] Update dependencies, include pipeline v0.33.2
  cloudevents/cmd/controller/main.go
  cloudevents/go.mod
  cloudevents/go.sum
  cloudevents/pkg/reconciler/pipelinerun/controller.go
  cloudevents/pkg/reconciler/pipelinerun/reconciler.go
  cloudevents/pkg/reconciler/pipelinerun/reconciler_test.go
Labels: approved, lgtm, size/XXL

#841 [pipeline/trusted-resources]Add admission webhook
  pipeline/trusted-resources/.gitignore
  pipeline/trusted-resources/README.md
  pipeline/trusted-resources/cmd/webhook_trusted_resource/main.go
  pipeline/trusted-resources/config/100-namespace.yaml
  pipeline/trusted-resources/config/200-clusterrole.yaml
  pipeline/trusted-resources/config/200-role.yaml
  pipeline/trusted-resources/config/200-serviceaccount.yaml
  pipeline/trusted-resources/config/201-clusterrolebinding.yaml
  pipeline/trusted-resources/config/201-rolebinding.yaml
  pipeline/trusted-resources/config/500-webhook-secret.yaml
  pipeline/trusted-resources/config/500-webhook-trusted-resources.yaml
  pipeline/trusted-resources/config/600-webhook.yaml
  pipeline/trusted-resources/config/config-signing-secret-path.yaml
  pipeline/trusted-resources/examples/1-test-taskrun.yaml
  pipeline/trusted-resources/examples/2-test-taskrun-oci-bundle.yaml
  pipeline/trusted-resources/examples/3-test-taskrun-taskref.yaml
  pipeline/trusted-resources/examples/4-test-taskrun_fail_verification.yaml
  pipeline/trusted-resources/examples/test_task.yaml
  pipeline/trusted-resources/go.sum
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
Labels: approved, lgtm, size/XL

#846 [pipeline/trusted-resources]Add signing for yaml files
  pipeline/trusted-resources/.gitignore
  pipeline/trusted-resources/README.md
  pipeline/trusted-resources/cmd/sign/main.go
  pipeline/trusted-resources/cmd/sign/sign_test.go
  pipeline/trusted-resources/examples/1-test-taskrun-signed.yaml
  pipeline/trusted-resources/examples/2-test-taskrun-oci-bundle-signed.yaml
  pipeline/trusted-resources/examples/3-test-taskrun-taskref-signed.yaml
  pipeline/trusted-resources/examples/4-test-taskrun_fail_verification.yaml
  pipeline/trusted-resources/go.mod
  pipeline/trusted-resources/pkg/trustedtask/sign.go
  pipeline/trusted-resources/pkg/trustedtask/sign_test.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
Labels: approved, lgtm, size/XXL

#849 [pipeline/trusted-resources]Clean config files
  pipeline/trusted-resources/config/200-clusterrole.yaml
  pipeline/trusted-resources/config/500-webhook-trusted-resources.yaml
Labels: approved, lgtm, size/M

#852 [pipeline/trusted-resources]Verify task OCI bundle
  pipeline/trusted-resources/README.md
  pipeline/trusted-resources/cmd/sign/main.go
  pipeline/trusted-resources/cmd/sign/sign_test.go
  pipeline/trusted-resources/examples/1-test-taskrun-signed.yaml
  pipeline/trusted-resources/examples/1-test-taskrun.yaml
  pipeline/trusted-resources/examples/2-test-taskrun-oci-bundle-signed.yaml
  pipeline/trusted-resources/examples/2-test-taskrun-oci-bundle.yaml
  pipeline/trusted-resources/examples/3-test-taskrun-taskref-signed.yaml
  pipeline/trusted-resources/examples/3-test-taskrun-taskref.yaml
  pipeline/trusted-resources/examples/4-test-taskrun_fail_verification.yaml
  pipeline/trusted-resources/examples/example-task.yaml
  pipeline/trusted-resources/examples/signed.yaml
  pipeline/trusted-resources/go.mod
  pipeline/trusted-resources/pkg/trustedtask/sign.go
  pipeline/trusted-resources/pkg/trustedtask/sign_test.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
  pipeline/trusted-resources/pkg/trustedtask/verify.go
  pipeline/trusted-resources/pkg/trustedtask/verify_test.go
Labels: approved, lgtm, size/XXL

#853 [pipeline/trusted-resources]Verify task from cluster at taskrun
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
Labels: approved, lgtm, size/L

#854 [pipeline/trusted-resources]Verify pipelinerun
  pipeline/trusted-resources/examples/4-test-pipelinerun.yaml
  pipeline/trusted-resources/examples/example-pipeline.yaml
  pipeline/trusted-resources/pkg/trustedtask/trustedpipelinerun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedpipelinerun_test.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
  pipeline/trusted-resources/pkg/trustedtask/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL
