Repository tektoncd/experimental, pull requests merged in 2022-10, with the labels that each got.

#904 Remove unused issue template
  .github/issue-template.md
Labels: size/S, approved, lgtm, kind/misc

#907 [concurrency] Add installation instructions
  concurrency/CONTRIBUTING.md
  concurrency/README.md
  concurrency/tekton/README.md
Labels: size/S, approved, lgtm

#906 Add "images" param to customtask release task
  tekton/customtask-release-pipeline.yaml
  tekton/publish-customtask.yaml
Labels: size/S, approved, lgtm

#905 [concurrency] Implement webhook and reconciler
  concurrency/README.md
  concurrency/cmd/controller/main.go
  concurrency/cmd/webhook/main.go
  concurrency/config/201-clusterrole.yaml
  concurrency/config/500-webhook-configuration.yaml
  concurrency/examples/pipelinerun.yaml
  concurrency/go.mod
  concurrency/go.sum
  concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go
  concurrency/pkg/reconciler/concurrency/controller.go
Labels: approved, lgtm, size/XL

#911 [concurrency] Support multiple cancelation strategies
  concurrency/README.md
  concurrency/cmd/webhook/main.go
  concurrency/config/500-webhook-configuration.yaml
  concurrency/examples/concurrencycontrol.yaml
  concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types.go
  concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types_test.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go
Labels: approved, lgtm, size/L

#909 [workflows] Add function to convert workflow to tekton triggers
  workflows/config/rbac.yaml
  workflows/config/workflows-el.yaml
  workflows/go.mod
  workflows/minimal.yaml
  workflows/pkg/apis/workflows/v1alpha1/workflow_types.go
  workflows/pkg/convert/convert.go
  workflows/pkg/convert/convert_test.go
Labels: approved, lgtm, size/L

#910 [workflows] reconciler logic + docs
  workflows/README.md
  workflows/cmd/run/README.md
  workflows/cmd/run/main.go
  workflows/config/201-clusterrole.yaml
  workflows/config/rbac.yaml
  workflows/config/workflows-el.yaml
  workflows/examples/npm-publish.yaml
  workflows/go.mod
  workflows/go.sum
  workflows/pkg/apis/workflows/v1alpha1/workflow_types.go
  workflows/pkg/apis/workflows/v1alpha1/workflow_validation.go
  workflows/pkg/convert/convert.go
  workflows/pkg/convert/convert_test.go
  workflows/pkg/reconciler/workflows/controller.go
  workflows/pkg/reconciler/workflows/workflows.go
  workflows/pkg/reconciler/workflows/workflows_test.go
  workflows/tekton/README.md
Labels: approved, lgtm, size/XL

#912 [concurrency] Merge mutating admission webhooks
  concurrency/cmd/webhook/main.go
  concurrency/config/500-webhook-configuration.yaml
Labels: approved, lgtm, size/M

#920 [concurrency] Add jerop to OWNERS
  concurrency/OWNERS
Labels: size/XS, approved, lgtm

#913 [concurrency] Add namespace allowlist
  concurrency/README.md
  concurrency/cmd/webhook/main.go
  concurrency/config/201-clusterrole.yaml
  concurrency/config/concurrency-config.yaml
  concurrency/pkg/apis/config/config.go
  concurrency/pkg/apis/config/config_test.go
  concurrency/pkg/apis/config/testdata/concurrency-config-all-namespaces.yaml
  concurrency/pkg/apis/config/testdata/concurrency-config-multiple-namespaces.yaml
  concurrency/pkg/apis/config/testdata/concurrency-config-one-namespace.yaml
  concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go
  concurrency/pkg/reconciler/concurrency/controller.go
Labels: approved, lgtm, size/L

#922 [workflows] Use PipelineRef from Tekton Pipelines
  workflows/examples/github-ci-workflow.yaml
  workflows/examples/npm-publish.yaml
  workflows/examples/workflow-example.yaml
  workflows/pkg/apis/workflows/v1alpha1/workflow_types.go
  workflows/pkg/apis/workflows/v1alpha1/zz_generated.deepcopy.go
  workflows/pkg/convert/convert.go
  workflows/pkg/convert/convert_test.go
Labels: approved, lgtm, size/L

#923 [concurrency] Add functionality to group by labels
  concurrency/examples/concurrencycontrol.yaml
  concurrency/examples/pipelinerun.yaml
  concurrency/go.mod
  concurrency/pkg/apis/concurrency/v1alpha1/concurrency_types.go
  concurrency/pkg/apis/concurrency/v1alpha1/zz_generated.deepcopy.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol.go
  concurrency/pkg/reconciler/concurrency/concurrencycontrol_test.go
Labels: approved, lgtm, size/L
