Repository tektoncd/experimental, pull requests merged in 2022-04, with the labels that each got.

#860 Add experimental directory for pipeline in a pod
  pipeline-in-pod/LICENSE
  pipeline-in-pod/OWNERS
  pipeline-in-pod/README.md
Labels: approved, lgtm, size/L

#862 [pipeline/trusted-resources] Add An Owner
  pipeline/trusted-resources/OWNERS
Labels: size/XS, approved, lgtm

#855 [pipeline/trusted-resources]Add config map watcher
  pipeline/trusted-resources/README.md
  pipeline/trusted-resources/cmd/webhook_trusted_resource/main.go
  pipeline/trusted-resources/pkg/config/config.go
  pipeline/trusted-resources/pkg/config/doc.go
  pipeline/trusted-resources/pkg/config/store.go
  pipeline/trusted-resources/pkg/config/store_test.go
  pipeline/trusted-resources/pkg/config/zz_generated.deepcopy.go
  pipeline/trusted-resources/pkg/trustedtask/trustedpipelinerun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedpipelinerun_test.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun_test.go
  pipeline/trusted-resources/pkg/trustedtask/verify.go
Labels: approved, lgtm, size/L

#865 [pipeline-in-pod] Timeouts.Pipeline support
  pipeline-in-pod/README.md
  pipeline-in-pod/examples/inline-pipeline-inline-tasks.yaml
  pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocated_pipelinerun_types_test.go
  pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocated_pipelinerun_validation.go
  pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocatedpipelinerun_types.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelineinpod.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/pod.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/run.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/run_test.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/status.go
  pipeline-in-pod/pkg/test/yaml_parsing.go
Labels: approved, lgtm, size/L

#807 Use cmpopts.IgnoreFields instead of IgnoreType.
  pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  task-loops/pkg/reconciler/tasklooprun/tasklooprun_test.go
  task-loops/test/tasklooprun_test.go
Labels: kind/bug, size/XS, approved, lgtm

#863 [pipeline/trusted-resources]Add KMS support
  pipeline/trusted-resources/README.md
  pipeline/trusted-resources/cmd/sign/main.go
  pipeline/trusted-resources/cmd/sign/sign_test.go
  pipeline/trusted-resources/config/config-signing-secret-path.yaml
  pipeline/trusted-resources/examples/example-task.yaml
  pipeline/trusted-resources/pkg/config/config.go
  pipeline/trusted-resources/pkg/config/store_test.go
  pipeline/trusted-resources/pkg/config/zz_generated.deepcopy.go
  pipeline/trusted-resources/pkg/trustedtask/trustedpipelinerun.go
  pipeline/trusted-resources/pkg/trustedtask/trustedtaskrun.go
  pipeline/trusted-resources/pkg/trustedtask/verify.go
Labels: approved, lgtm, size/L

#818 Fix install url in pipelines-in-pipelines README
  pipelines-in-pipelines/README.md
Labels: size/XS, approved, lgtm, lifecycle/stale, ok-to-test

#869 [Pipeline-in-pod] workspaces support
  pipeline-in-pod/README.md
  pipeline-in-pod/examples/inline-pipeline-inline-tasks.yaml
  pipeline-in-pod/examples/inline-pipeline-taskrefs.yaml
  pipeline-in-pod/examples/pipelineref.yaml
  pipeline-in-pod/go.sum
  pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/colocatedpipelinerun_types.go
  pipeline-in-pod/pkg/apis/colocatedpipelinerun/v1alpha1/zz_generated.deepcopy.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/apply.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/entrypoint.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/ordering.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelineinpod.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelinespec.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/pod.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/status.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/taskspec.go
  pipeline-in-pod/pkg/reconciler/pipelineinpod/validate.go
Labels: approved, lgtm, size/XL
